version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=issuetracker
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    restart: on-failure
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
    restart: on-failure
    links:
      - db
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
    restart: on-failure
    ports:
      - "1000:80"
    links:
      - web
volumes:
  postgres:
