# Generated by Django 2.0.6 on 2018-06-24 12:44

from django.db import migrations


def create_staff_group(apps, schema_editor):
    """Create (if needed) and configure `Staff` Group."""
    def get_or_create_permission(codename, name, app_label, model_name):
        return Permission.objects.get_or_create(
            codename=codename,
            name=name,
            content_type=ContentType.objects.get_or_create(
                app_label=app_label, model=model_name)[0]
        )[0]

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    # Manual view permissions creation is needed in case this migration
    # is applied at the same time those models are created, because
    # `admin_view_permission` creates those permission only on
    # `post_migrate`, which is sent the the end of `migrate` command
    # execution.
    permissions = [
        get_or_create_permission(
            'view_issue', "Can view issue", 'core', 'Issue'),
        get_or_create_permission(
            'view_issuecategory', "Can view issuecategory", 'core',
            'IssueCategory'),
        get_or_create_permission(
            'view_issuestatus', "Can view issuestatus", 'core', 'IssueStatus'),
        ]
    group = Group.objects.get_or_create(name="Staff")[0]
    group.permissions.add(*permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fill_issue_solved_at'),
        ('auth', '0001_initial'),  # Models `Group` and `Permission`.
    ]

    operations = [
        migrations.RunPython(create_staff_group, migrations.RunPython.noop)
    ]
